name: pipeline

on: [push, pull_request]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["9.2", "9.4", "9.6"]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: "3.10"

      - name: Formatting
        uses: mrkkrp/ormolu-action@v16

      - name: Set up HLint
        uses: haskell/actions/hlint-setup@v2

      - name: "Run HLint"
        uses: haskell/actions/hlint-run@v2
        with:
          path: '["src/", "app/", "test/"]'

      - name: Configure
        run: cabal configure --enable-tests --enable-benchmarks --enable-documentation --test-show-details=direct --write-ghc-environment-files=always

      - name: Freeze
        run: cabal freeze

      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-ghc-${{ hashFiles('cabal.project.freeze') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ hashFiles('cabal.project.freeze') }}-
            ${{ runner.os }}-ghc-

      - name: Install dependencies
        run: cabal build all --only-dependencies

      - name: Build
        run: cabal build all

      - name: Test
        run: cabal test all

  stack:
    name: stack / ghc 9.6
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: haskell-actions/setup@v2
        with:
          stack-version: latest
          ghc-version: "9.6"
          enable-stack: true

      - uses: actions/cache@v4
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-ghc96-stack

      - name: Build
        run: stack build --test --no-run-tests

      - name: Test
        run: stack test
