name: pipeline

on: [push, pull_request]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["9.0", "9.2", "9.4"]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Formatting
        uses: mrkkrp/ormolu-action@v9

      - name: Set up HLint
        uses: haskell/actions/hlint-setup@v2
      
      - name: 'Run HLint'
        uses: haskell/actions/hlint-run@v2
        with:
          path: '["src/", "app/", "test/"]'

      - name: Configure
        run: cabal configure --enable-tests --enable-benchmarks --enable-documentation --test-show-details=direct --write-ghc-environment-files=always

      - name: Freeze
        run: cabal freeze

      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-ghc-${{ hashFiles('cabal.project.freeze') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ hashFiles('cabal.project.freeze') }}-
            ${{ runner.os }}-ghc-

      - name: Install dependencies
        run: cabal build all --only-dependencies

      - name: Build
        run: cabal build all 

      - name: Test
        run: cabal test all

  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: haskell/actions/setup@v2
        with:
          stack-version: latest
          enable-stack: true
          stack-no-global: true

      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Build
        run: stack build --test --no-run-tests

      - name: Test
        run: stack test 
